# Some defaults. Commented are default values for some settings you might want to change
# Check: https://github.com/jekyll/jekyll/blob/df8458275de4dc3d0f9b92c5247ff20832d1cc8e/lib/jekyll/configuration.rb

# = REMEMBER: Github exposes extra goodies under site.github
# https://help.github.com/articles/repository-metadata-on-github-pages

# = My Custom Settings:
author: 'David Hund'
site_name: 'David Hund'
site_domain: 'http://davidhund.com'
ga_code: 'UA-5040498-12'

# = Jekyll (Default) Settings:
source:      .
destination: ./_site
exclude:
- '.DS_Store'
- 'node_modules'
- 'bower_components'
- '*.sql'
- '*.sass'
- '*.scss'
- '.sass-cache'
- 'gulp*'
- 'grunt*'
- 'package.json'
- 'bower.json'
- 'README.md'
- 'HOWTO.md'
- 'EXAMPLE.CNAME'
- 'Gemfile'
- 'Gemfile.lock'

# include:     ['.htaccess']
keep_files:  ['.git','.svn']
permalink:   pretty

relative_permalinks: true

# Change baseurl to /gh-subfolder when publishing on gh-pages.
# See: _config-gh-pages.yml
# baseurl:     /davidhund.com
baseurl:     ''
url: http://davidhund.com

# url: http://localhost:4000
# host: 0.0.0.0
# port: 4000
# future:      true
# safe:        false
# plugins:     ./_plugins
# lsi:         false
# pygments:    false
markdown:    kramdown
kramdown:
  input: GFM
